name: springboard-unfpa
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
virtualenv_prefix: springboard
pip:
 - gunicorn
dependencies:
 - python-yaml
 - cmake
 - libssl-dev
 - libffi-dev
